//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodManagement.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodManagement.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải bắt đầu bằng {1}!.
        /// </summary>
        public static string CodeInvalid {
            get {
                return ResourceManager.GetString("CodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã tồn tại! Vui lòng kiểm tra lại!.
        /// </summary>
        public static string DataExist {
            get {
                return ResourceManager.GetString("DataExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ! Vui lòng kiểm tra lại!.
        /// </summary>
        public static string DataInValid {
            get {
                return ResourceManager.GetString("DataInValid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công.
        /// </summary>
        public static string LoginSuccess
        {
            get
            {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không đúng. Vui lòng thử lại!
        /// </summary>
        public static string LoginFail
        {
            get
            {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} không được vượt quá {1} ký tự!  .
        /// </summary>
        public static string DataMaxLengthError {
            get {
                return ResourceManager.GetString("DataMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không tồn tại! Vui lòng thử lại..
        /// </summary>
        public static string DataNotExist {
            get {
                return ResourceManager.GetString("DataNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được phép để trống! Vui lòng nhập &apos;{1}&apos;!.
        /// </summary>
        public static string DataNullError {
            get {
                return ResourceManager.GetString("DataNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu phù hợp!.
        /// </summary>
        public static string DataResponseNull {
            get {
                return ResourceManager.GetString("DataResponseNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được lớn hơn hiện tại!.
        /// </summary>
        public static string DateInvalid {
            get {
                return ResourceManager.GetString("DateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu thành công!.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không đúng định dạng!.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên này không tồn tại hoặc đã bị xóa! Vui lòng kiểm tra lại!.
        /// </summary>
        public static string EmployeeNotExist {
            get {
                return ResourceManager.GetString("EmployeeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra! Vui lòng lên hệ với quán để được hỗ trợ.
        /// </summary>
        public static string ExceptionError {
            get {
                return ResourceManager.GetString("ExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy dữ liệu thành công!.
        /// </summary>
        public static string GetSuccess {
            get {
                return ResourceManager.GetString("GetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không đúng định dạng!.
        /// </summary>
        public static string IdInvalid {
            get {
                return ResourceManager.GetString("IdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản này đã có phát sinh trong phiếu thu/chi. Bạn không thể xóa tài khoản này..
        /// </summary>
        public static string Incurred {
            get {
                return ResourceManager.GetString("Incurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu hiển thị..
        /// </summary>
        public static string NoContent {
            get {
                return ResourceManager.GetString("NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không đúng định dạng!.
        /// </summary>
        public static string PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới dữ liệu thành công!.
        /// </summary>
        public static string PostSuccess {
            get {
                return ResourceManager.GetString("PostSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu thành công!.
        /// </summary>
        public static string PutSuccess {
            get {
                return ResourceManager.GetString("PutSuccess", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Hết hạn đăng nhập phiên. Vui lòng đăng nhập lại!.
        /// </summary>
        public static string LoginLimit
        {
            get {
                return ResourceManager.GetString("LoginLimit", resourceCulture);
            }
        }
    }
}
